### ISSUE TITLE
Refactor `diagnostic_utils` package content

### ISSUE THREAD

**Issue by brianhenn** [ai2cm/fv3net#1031]
The `diagnostic_utils` package was separated out to avoid duplicating functions used by `trianing_data_diags` and `offline_ml_diags`, but `training_data_diags` is basically defunct and should be removed (https://github.com/VulcanClimateModeling/fv3net/issues/1030), so the functions in `diagnostic_utils` tend to be either a) pretty tightly coupled to `offline_ml_diags` or b) general enough to be broadly useful. The first should probably be refactored to `offline_ml_diags` and the second maybe to `vcm`, so that this package doesn't have to be maintained separately.

**Comment by oliverwm1** [comment]
This package has been removed. The relevant functions were refactored to `workflows/diagnostics/fv3net/offline` or `workflows/diagnostics/fv3net/_shared`.
