### ISSUE TITLE
Use new *Coarsen.reduce functionality for coarsening with custom reductions

### ISSUE THREAD

**Issue by spencerkclark** [ai2cm/fv3net#1048]
Xarray 0.17.0 adds a `.reduce` method to `DataArrayCoarsen` and `DatasetCoarsen`, which natively enables coarsening DataArrays and Datasets with custom reduction functions.  This obviates some functions in vcm, namely [`xarray_block_reduce` and `horizontal_block_reduce`](https://github.com/VulcanClimateModeling/fv3net/blob/fd446563574e23978ac9137e1ac4e8232edc5c80/external/vcm/vcm/cubedsphere/coarsen.py#L463-L554) (as well as some associated private functions).  Some care will be needed to maintain dask compatibility for some operations, but it should hopefully be possible without too much trouble.

The main motivation for doing this is that it should allow us to drop the dependency on scikit-image.

**Comment by spencerkclark** [comment]
@mcgibbon given that @nbren12 vendored the required functionality from scikit-image (removing our dependency on it) I consider this refactor to be low priority (if necessary at all).  I would be fine with closing this if we'd like to clean up the issue tracker.

**Comment by mcgibbon** [comment]
If the refactor isn't necessary I'd say to close it to keep things clean, if you think this is something I should spend time on in let's say the next two months then it can stay open. If not I'd think it isn't likely to ever get done.

**Comment by spencerkclark** [comment]
Yeah, I don't think this is worth spending your time on.  Let's close.
