### ISSUE TITLE
Is interpolation always the right choice for prescribing the surface radiative fluxes?

### ISSUE THREAD

**Issue by spencerkclark** [ai2cm/fv3net#1181]
In looking at some output from early parts of the latest nudge-to-25-km simulations, I've noticed a similar pattern of sawtoothing in the net column shortwave radiation that we saw in early nudge-to-3-km simulations where we prescribed the surface radiative fluxes.  

![interp-vs-bfill-radiation-2](https://user-images.githubusercontent.com/6628425/117302623-d687c600-ae49-11eb-929d-79e2cdfba9cf.png)

In the nudge-to-3-km case, we were able fix this by aligning the radiation timesteps of the fine and coarse models (by both starting the nudged coarse run on an even hour, and ensuring the radiation timesteps were the same in the fine and coarse runs).  I have been careful to do this in the nudge-to-25-km simulations; however, this is not enough, because in the nudge-to-25-km case the model physics timestep requires that we interpolate the reference surface radiative fluxes every other timestep.  What this means is that while the TOA shortwave radiation has a discontinuous jump every radiation timestep, the surface shortwave fluxes vary more smoothly, and thus the difference -- the net column shortwave radiation -- contains O(100 W/m^2) spikes.

A possible fix for this would be to use `Dataset.reindex` with `mode="bfill"` instead of `Dataset.interp`.  This would mean that for any model time that did not exist in the reference dataset, we would prescribe the value from the closest valid time in the future.  An illustration that this fixes this issue can be found in the panel on the right of the included plot.

Some questions would be:
- Is this worth caring about?
- Would we be OK using this method for the precipitation as well, or would we prefer to use interpolation there?
- Is `reindex` with `mode="bfill"` always the right choice?  I suppose with less frequent reference data, interpolation might be more appropriate, despite the sawtoothing issue.

**Comment by nbren12** [comment]
@spencerkclark Is this still an issue?

**Comment by spencerkclark** [comment]
It's something to keep in mind, though I think we agreed in a Slack conversation (buried in the past now) that this was not worth worrying about, since the the atmosphere doesn't directly feel the implied column radiative heating by prescribing the surface radiative fluxes to the land surface.  Therefore I think we can close this issue.

It does make me realize that one difference @AnnaKwa may be running into with the PIRE dataset is that we only have reference interval-average radiative fluxes sampled every three hours.  In the original nudge-to-3-km work and in my nudge-to-25-km work, we have radiative flux data every 15 minutes.

**Comment by nbren12** [comment]
Ok. I will close this so we can just keep it in mind.
