### ISSUE TITLE
Prognostic run "prephysics" is a bit confusing

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#1211]
It is hard to know what should go in`config.prephysics`:
https://github.com/VulcanClimateModeling/fv3net/blob/a24d15ef763a2a157e62738dbf09738cb85fe8ad/workflows/prognostic_c48_run/runtime/config.py#L27

As a user, I don't want to know if something is done pre or post physics, I just want to know that the intended effect is achieved. Would it be possible to break down this section more finely, so that it can be more easily understood. E.g.

```
config.surface:
   radiation:...
   surface_precipitation: ...
```

**Comment by mcgibbon** [comment]
Closing with feedback from @nbren12
