### ISSUE TITLE
Save output prediction dim/coordinate info in predictors

### ISSUE THREAD

**Issue by AnnaKwa** [ai2cm/fv3net#1331]
Restoring stacked model predictions into the correct unstacked coordinates currently assumes that the input data to the predict methods shares all the coordinates of the output data (https://github.com/VulcanClimateModeling/fv3net/blob/a300c4633f830a1a8522cf1957b55c1182ed51e0/external/fv3fit/fv3fit/_shared/stacking.py#L137). 

This might not always be true, so we should have some object that saves this information at fit time for all Predictors (DenseModel sort of does this already with its packers). This would replace calls of the function `match_prediction_to_input_coords(input, prediction)`.

**Comment by mcgibbon** [comment]
We shouldn't ever run into a situation where we're predicting an output with a dimension that is not present in the inputs, so we can close this.
