### ISSUE TITLE
move weighted averaging utilities to vcm

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#1390]
I often need to take weighted averages in jupyter notebooks, but currently this functionality is in a somewhat obscure location `diagnostic_utils.utils.weighted_average`. Would be great to have `vcm.weighted_average`.

**Comment by oliverwm1** [comment]
Also the zonal mean function:

https://github.com/ai2cm/fv3net/blob/b11606c5058e91739b516848303b1ea2b3cd8900/workflows/diagnostics/fv3net/diagnostics/prognostic_run/compute.py#L126-L132

**Comment by oliverwm1** [comment]
> I normally use vcm.select.zonal_average_approximate to take zonal means in notebooks:

Oh nice, I was not aware of this function. We should refactor the prognostic run diagnostics to use it.

**Comment by nbren12** [comment]
Is the weighted average interface in our current version of xarray?

**Comment by nbren12** [comment]
The `select` module is pretty poorly named along with `convenience`. Probably worth pulling some of those apis to the top level.
