### ISSUE TITLE
Make prognostic run dev environment work with application default credentials

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#1427]
The prognostic run development enviroment (docker-compose) needs service account credentials. It should be possible to use with the keys configured by `google auth application-default login`.

**Comment by mcgibbon** [comment]
Is this resolved by deleting the docker-compose.yml?

**Comment by nbren12** [comment]
The solution is to bind-mount in these keys: `~/.config/gcloud/application_default_credentials.json` and point to it with the GOOGLE_APPLICATION_CREDENTIALS. Either that or bind-mount in the whole `~/.config/gcloud` folder.

**Comment by mcgibbon** [comment]
OK, the top-level docker system already does that so this should be handled by deleting docker-compose.yml in #1837 and replacing it with the top-level enter target.

**Comment by mcgibbon** [comment]
Resolved by #1837.
