### ISSUE TITLE
Making NudgingConfig.restarts_path non optional

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#1449]
Okay, but it is still misleading, since a `NudgingConfig` dataclass with no `restarts_path` specified will lead to a failed run. Can you add a TODO to remove the `Optional`?

_Originally posted by @oliverwm1 in https://github.com/ai2cm/fv3net/pull/1444#discussion_r737641907_

This will break backwards compatibility.

**Comment by oliverwm1** [comment]
Closed by #1464
