### ISSUE TITLE
Make report for 10 day run with microphysics emulator

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#1453]
This run is initialized on Aug 11 and run with the model located here: `gs://vcm-ml-experiments/2021-10-14-microphsyics-emulation-paper/models/all-tends-limited/all-tends-limited-dense/model.tf`

- run outputs: gs://vcm-ml-scratch/2021-10-14-microphsyics-emulation-paper/2021-10-27/6ea8b19fd4f740c19cb6a15b27e881db
- [wandb configuration](https://wandb.ai/ai2cm/crapcrap/runs/1bb13kgx/overview?workspace=user-nbren12).

We need to run the reports for this run to see how it did.

**Comment by frodre** [comment]
W & B report on our baseline coming out of the summer

https://wandb.ai/ai2cm/microphysics-emulation/reports/Microphysics-Emulation-Perfomance-Nov-15-Baseline--VmlldzoxMjI4MDg0
