### ISSUE TITLE
Diagnose precipitation from microphysics tendencies

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#1485]
For the zhao-carr scheme, the column-integrated total moisture sink and the surface precipitation are identical. See the paper and this [notebook](
https://github.com/ai2cm/explore/blob/master/noahb/emulation/microphysics/2021-11-00-surface%20precip-vs-column%20tendencies.ipynb).

It is not necessary to train a separate ML model for the precip because of this.

**Comment by nbren12** [comment]
cc @frodre

**Comment by frodre** [comment]
Nice work.  Glad to see this should be good for precip output.

**Comment by nbren12** [comment]
The 3d tendency skill worsens more quickly than the precip-trained model: https://wandb.ai/ai2cm/microphysics-emulation/runs/2ab33um4?workspace=user-nbren12.

**Comment by nbren12** [comment]
I am training a model to do this: https://wandb.ai/ai2cm/microphysics-emulation/runs/2gk2hxju?workspace=user-nbren12

I then need to produce some reports for it.
