### ISSUE TITLE
Enhance feature set of microphysics emulation

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#1491]
The zhao-carr microphysics internally computes a relative humidity tendency based on the temperature and humidity state saved between the large-scale condensation (`gscond`) and precipitation `precpd` schemes. Here are some notes on how the scheme works:

```
# table of names
# GFS_physics_driver, gscond, and call_py_fort
|phys_f3d_1 | tp  |  air_temperature_two_time_steps_back | 
|phys_f3d_2 | qp  | specific_humdity_two_time_steps_back |
|phys_f3d_3 | tp1 | air_temperature_at_previous_time_step |
|phys_f3d_4 | qp1 | specific_humidity_at_previous_time_step |
```

# gscond

These extra time points are set and used in `gscond.f`. These are the parts of the code using them:

Line 272: compute tendencies

```fortran
          at    = (tik-tp(i,k)) * rdt
          aq    = (qik-qp(i,k)) * rdt
          ap    = (pres-pp0)    * rdt
```

Lin 450: condensation calculation
```fortran
             cond   = (ac-ad)*(af*aq-ai*at+ae*qik*ap)/(ac*(af+ag))
!-----------check & correct if over condensation occurs-----------------
             condi  = (qik   -u00ik   *qc*1.0)*rdt
             cond   = min(cond, condi)
```

Line 473: update to temperature/humidity
```fortran
          t(i,k)   = t(i,k)   + elv*rcp*cone0
          q(i,k)   = q(i,k)   - cone0
```

Updating states. If physics step is bigger than dynamics step

Line 488: storing humidity
```fortran
            tp(i,k)  = tp1(i,k)
            qp(i,k)  = qp1(i,k)
            tp1(i,k) = t(i,k)
            qp1(i,k) = max(q(i,k),epsq)
```

Else

``` Fortran
            tp(i,k)  = t(i,k)
            qp(i,k)  = max(q(i,k),epsq)
!           qp(i,k)  = q(i,k)
            tp1(i,k) = tp(i,k)
            qp1(i,k) = qp(i,k)
```

# interpretation

## physics timestep larger than the dynamics step

Let -+ denote before/after the zhao carr scheme is called. Then, the update rule in L488 does this:

    tp[n, +] = tp1[n, -]
    tp1[n, +] = t[n, +]

The action of the timestep is

    tp[n, -] = tp[n-1,+]
    tp1[n,-] = tp1[n-1,+]

So `tp[n,-] = tp[n-1,+] = tp1[n-1, -] = tp1[n-2,+] = t[n-2,+]`

This rule doesn't make much sense to me. The formula for the time derivative is
not altered based on this formula. What is the significance of 2 steps?  What if
the physics timestep is say 3 times larger than the dynamics step.

## otherwise 

In this most common case the physics and dynamics timesteps so we follow the second rule

    tp[n, +] = t[n, +]
    tp1[n, +] = tp[n, +]

The action of the timestep is

    tp[n, -] = tp[n-1,+]
    tp1[n,-] = tp1[n-1,+]

This rule makes more sense to me. It does not appear that the rule above could
work if the physics is called more than twice.

# Conclusion

We should also save and predict `t[n,+]`. Also, the names used by call_py_fort are not accurate. If I am right, `tp1` and `tp` should be identical, and they do not represent the state in the previous timestep, but rather the state at the end of the last time `gscond` was called.

**Comment by nbren12** [comment]
I have verified that `tp[n,-]` and `tp1[n,-]` are identical for our configuration. See this [notebook](https://github.com/ai2cm/explore/blob/master/noahb/emulation/microphysics/2021-11-03-verify%20tbd%20data.ipynb).

**Comment by nbren12** [comment]
Related to #1494

**Comment by frodre** [comment]
Thanks for the nice documentation relating to the internal process of ZC

**Comment by nbren12** [comment]
No problem. It's pretty confusing stuff (esp the logic with larger physics than dynamics timesteps).

**Comment by nbren12** [comment]
A new dataset has been generated at `gs://vcm-ml-experiments/microphysics-emulation/2021-11-24/microphysics-training-data-v3-training_netcdfs``
