### ISSUE TITLE
Verify that RNN is not actually "downward dependent" using jacobian plots/tests

### ISSUE THREAD

**Issue by frodre** [ai2cm/fv3net#1522]
The design of the microphysics model RNNBLock and FieldOutput "undoes" the vertical dependence structure we tried to enforce.

**Comment by frodre** [comment]
Plots show that d(output[i])/d(input[j]) != 0 for i > j

![image](https://user-images.githubusercontent.com/1440875/144109638-856a0378-ad3c-46d6-a881-74880ed2496b.png)

https://github.com/ai2cm/explore/blob/master/andrep/microphysics/2021-11-29-top-down-gradient-constraint.ipynb

**Comment by nbren12** [comment]
Cool plots! I'm also surprised by how noisy the jacobian is for some fields. Maybe some regularization could help.
