### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#1529]
Master currently failed because of a flaky test:
- [circle ci job](https://app.circleci.com/pipelines/github/ai2cm/fv3net/10362/workflows/35d181c5-633c-4f33-a274-db95af780cfb/jobs/90413?invite=true#step-110-217)
Probably just need to add some bounds to the `hypothesis` generated test cases.

**Comment by nbren12** [comment]
cc @AnnaKwa I know you've fixed similar bugs in the past.

**Comment by oliverwm1** [comment]
I think this is a duplicate of #1469 which was never actually fixed.

**Comment by AnnaKwa** [comment]
I think the above PR should actually resolve it this time.
