### ISSUE TITLE
emulation: training runs out of memory and crashes after epochs

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#1532]
The ML training for the conservative ML model (and maybe others) keeps crashing after running for 8 hours but before saving the ML model! See this: https://wandb.ai/ai2cm/microphysics-emulation/runs/7rgrn7jp?workspace=user-nbren12

The memory usage spikes at the end and eventually exceeds the k8s imposed limits.

**Comment by nbren12** [comment]
See the memory usage profile at the end of [these logs](https://wandb.ai/ai2cm/microphysics-emulation/runs/15uf548s/logs?workspace=user-nbren12). This suggests the `score_model` functions incur extra memory.

**Comment by frodre** [comment]
This is likely resolved by #1548 updates to the Argo memory limits and separates the scoring to ease retries.  Runs successfully with an RNN which has quite memory hungry scoring.
