### ISSUE TITLE
Include gfortran in conda environment

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#1637]
`make create_environment` fails on systems without gfortran installed when building the `vcm.mappm` extension:
```
    warning: build_ext: f77_compiler=None is not available.

    building 'vcm.mappm' extension
    error: extension 'vcm.mappm' has Fortran sources but no Fortran compiler found
```

**Comment by oliverwm1** [comment]
related: #1384

**Comment by mcgibbon** [comment]
On my M1 macbook, I cannot use gfortran. Will need to make this an optional import, at least. Does not work through docker, either.
