### ISSUE TITLE
Emulation: intermediate variables are present in `config.model_variables`

### ISSUE THREAD

**Issue by frodre** [ai2cm/fv3net#1658]
I am running into an issue when configuring a basic emulation model w/ a difference-transformed variable on master.  

```
Exception has occurred: KeyError
'temperature_gscond_difference'

During handling of the above exception, another exception occurred:
```

I was wondering if there a was a reason we stopped removing the "to" variable name from the `backwards_names` return value (e.g., for [Difference](https://github.com/ai2cm/fv3net/blob/dfaa394707dde2e0b18b6cf70f8a803a7308660a/external/fv3fit/fv3fit/emulation/transforms/transforms.py#L35))?  That would be consistent with converting an intermediate variable to dependencies in the `requested_names`, I think. 

Right now it provides all the variables back in `requested_names` (e.g., `before`, `after`, `to`) and the xarray lookup fails in the initial data loading when trying to find the `to` variable name.

@nbren12 Let me know when you get back.  In the interim I'll adjust so it works how I think it should.

**Comment by nbren12** [comment]
Is this still an issue? What yaml are you using?

**Comment by nbren12** [comment]
Ah i think i see the problem. We need to remove `self.to` from the set in this line:
https://github.com/ai2cm/fv3net/blob/dfaa394707dde2e0b18b6cf70f8a803a7308660a/external/fv3fit/fv3fit/emulation/transforms/transforms.py#L35

**Comment by frodre** [comment]
Yep, that's it.  I was just wondering if there was a reason it was added back in vs. the previous implementation when the differencing was in the conditional transform.  I'll just PR the adjustment.

**Comment by nbren12** [comment]
Not intentional at all! It's a shortcoming of the backward_names API that makes it easy to introduce this kind of bug.
