### ISSUE TITLE
fv3fit: shuffling test is flaky

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#1735]
@mcgibbon I just got a test failure on the new training loop randomness test:
```
FAILED tests/test_training_loop.py::test__shuffle_batched_tfdataset - assert (-0.3750280852770701 ** 2) < 0.1
```

Should we set the random seed or relax the 0.1 threshold or both?

**Comment by nbren12** [comment]
or delete the test?

**Comment by mcgibbon** [comment]
I think adding more batches and increasing the threshold should solve it.

I was hoping setting the random seed would be good enough.

**Comment by nbren12** [comment]
maybe there are more sources of randomness
