### ISSUE TITLE
Random Forest model predicts dataset with a too-large z dim

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/fv3net#1742]
See failing test on this PR: #1741

The RF model 'predict' method sometimes returns a dataset with the wrong z-dim length. This does not happen if the RF only has one output. For two outputs, it predicts a dataset with a z-dim length that is twice as long as it should be. This bug does not exist prior to #1685.

cc @mcgibbon

**Comment by brianhenn** [comment]
I found this as well ... have a potential fix in the works (PackerInfo serializes the features wrong for RF models).
