### ISSUE TITLE
improve colors in prognostic run report

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#1765]
not colorblind friendly and yellow is hard to see. Here is an example of a good colorscheme: https://gist.github.com/nbren12/585e73cb5543568bc83f220f85890870

No bokeh example though.

could also change the background color to improve contrast.

**Comment by brianhenn** [comment]
@nbren12  [here's](https://storage.googleapis.com/vcm-ml-public/brianh/test-prog-report/f312745deaa8/index.html) an example report with the modified color scheme, gray background, and gridlines.
