### ISSUE TITLE
Slow prognostic run image builds

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#1775]
The prognostic run image often takes a long time to build. For some reason, docker layer caching seems to regularly fail. In the past we relied on fv3gfs-fortran/wrapper to build the basic dependencies, but for backwards compatibility reasons the DSL team is reticent to allow updates to the fv3gfs-fortran images (which are now only used for checksums tests upstream). To allow upgrading to python3.8, we refactored all the docker logic to fv3net.

We could speed things up by creating a base-image with ESMF, FMS, and the other basic fortran dependencies (i.e. things we almost never change), this will only need to be updated every 2 years or so to change the base OS. We should not include FV3 in this image, since we change it pretty frequently. I think similar multi dockerfile/image architectures didn't work well for us in the past because:
1. we included high-frequency code (FV3) with low-frequency code (ESMF)
2. complicated integrations with makefiles and CI

To avoid (2), we could just manually build/push the base image, or we could build it in an another repo (e.g. https://github.com/ai2cm/packages), whose build system only gets triggered on changes there.

cc @oliverwm1

**Comment by oliverwm1** [comment]
Yeah it is a bit silly how often we are building ESMF in CI. Isolating the slow-changing dependencies to a docker image that is defined elsewhere seems like a good plan to me.

**Comment by nbren12** [comment]
This may have sped-up the build times in CI: 8cf4d2de9045da00146073019b5aeaeef130b010.

I still notice it wanting to recompile everything locally sometimes, but maybe there is some state on my VM messing that up for me.

**Comment by nbren12** [comment]
huh here is a recent build that missed the cache: https://app.circleci.com/pipelines/github/ai2cm/fv3net/11780/workflows/b869f1cd-d486-4e4a-be53-72938d3efa99/jobs/104991

**Comment by mcgibbon** [comment]
Adding a base image to push-pull is a good pattern, we do this on the DSL side.
