### ISSUE TITLE
prognostic run: python timings not output

### ISSUE THREAD

**Issue by brianhenn** [ai2cm/fv3net#1785]
We have [python wrapper timing](https://github.com/ai2cm/fv3net/blob/8857cd27a4e957514b8311275055911186a02226/workflows/prognostic_c48_run/runtime/loop.py#L383) in the prognostic run loop, but the function to log it is not currently called. It looks like we switched from calling `loop.cleanup()` (includes logging python timing) to `wrapper.cleanup()` (doesn't include it) at some point to avoid a gc/mpi bug; we should refactor timing logging call to somewhere appropriate to bring it back.

**Comment by nbren12** [comment]
Also would be nice to output the timings in a more structure format (e.g. json) so that we can make plots etc.
