### ISSUE TITLE
Prognostic run tests fail via some entrypoints lacking FSSPEC_GS_REQUESTER_PAYS

### ISSUE THREAD

**Issue by brianhenn** [ai2cm/fv3net#1802]
There are several ways to get into the prognostic run container to run the tests (`make enter_prognostic_run && pytest`, `test_prognostic_run`, `image_test_prognostic_run`, `cd workflow/prognostic_c48_run && make test`, etc. Running the tests requires that `FSSPEC_GS_REQUESTER_PAYS=vcm-ml` be set, but currently only `image_test_prognostic_run` sets this variable upon entering the container, so the others fail. We should simplify the number of entrypoints and ensure that the variables needed for the tests always get set.

**Comment by mcgibbon** [comment]
Resolved by #1837.
