### ISSUE TITLE
Difficulty reproducing prognostic run environment locally

### ISSUE THREAD

**Issue by AnnaKwa** [ai2cm/fv3net#1810]
I ran into [an error ](https://console.cloud.google.com/logs/query;query=%22multiyear-climat-sst-stable-mae-prog-run-7333a4b7616a-2544845185%22;timeRange=2022-04-28T18:21:00.883Z%2F2022-04-28T19:21:00.883Z;cursorTimestamp=2022-04-28T19:20:35.088346007Z?project=vcm-ml&folder=true&organizationId=916291154139) when I submitted a prognostic run argo workflow with commit `ffe4f5a3ee699c0f16aa32aa3603c6325de34d22`. The error itself is its own issue, I opened this issue because I have been unable to reproduce the error locally and can't figure out how my local prog run environment is different from the container that the argo submitted job ran on.

I checked using `kubectl describe pod ... ` that the failed job was using image `ffe4f5`. When trying to debug locally I ran in the same image; `docker-compose run ...` using the same image with a scratch directory and my credentials bind mounted. Using `runfv3 run-native` with the same fv3config copied from the failed remote rundir (aside from editing the layout to use 6 cores), I did not encounter the error. 

Are there any other considerations that need to be taken when trying to reproduce the prognostic run environment?

**Comment by brianhenn** [comment]
Agree that is perplexing, couple questions:

> (aside from editing the layout to use 6 cores)
Is the cluster job using 24 cores? Do you still get the error there if it uses 6?

> When trying to debug locally I ran in the same image; docker-compose run ... using the same image with a scratch directory and my credentials bind mounted. 

How did you obtain the image locally? I have confused myself in the past by building the image locally with uncommitted changes on the same prior commit SHA has something built in CI. The local image will have the same tag but different contents as the CI-built one in that circumstance, so just wanted to rule that out.

**Comment by oliverwm1** [comment]
Sometimes I've found `docker-compose` a bit too magical... hard to know exactly what image it is using. Maybe try vanilla `docker run` on the image you pulled from GCR?

Could hack the `enter_prognostic_run` rule to work for you (delete the bind-mounts, specify the image tag you want):

https://github.com/ai2cm/fv3net/blob/1d5be16282cb354f43f71ab19137f9291ec3d735/Makefile#L86-L96

**Comment by brianhenn** [comment]
Good point, I think the caching for `docker-compose build/run` is not the same as the caching for `docker build/pull/run`. So `docker-compose run` may result in entering a different image than `docker pull ... && docker run ...`

**Comment by brianhenn** [comment]
I don't know if others have smarter ways of checking this? But to confirm I'm in the image I think I'm in, I will often run a short python snippet within it that executes something I know to be unique about that particular image.

**Comment by AnnaKwa** [comment]
Hmm... still no success reproducing it. 

For good measure I tested the argo submitted job with 6 cores (still had the same error, so that wasn't it).

Tested again locally, and still couldn't reproduce the error: this time I directly copied the `fv3config.yml` from the failed run and entered the prognostic run container using
```
docker run \
    --tty \
    --interactive \
    --rm \
    -v ${GOOGLE_APPLICATION_CREDENTIALS}:/tmp/key.json \
    -v /Users/annak/Code/fv3net/scratch:/fv3net/scratch \
    -e GOOGLE_APPLICATION_CREDENTIALS=/tmp/key.json \
    -e FSSPEC_GS_REQUESTER_PAYS=vcm-ml \
    -w /fv3net/scratch/2022-04-27-prog-rad-debug \
    us.gcr.io/vcm-ml/prognostic_run:ffe4f5a3ee699c0f16aa32aa3603c6325de34d22 bash 
```
where I copied the image directly from the argo annotations.

**Comment by AnnaKwa** [comment]
Noah suggested it might be `runfv3 append` versus `runfv3 run-native`... that was it. A now-fixed bug in the step metadata was modifying config to add the prephysics model to the regular ml model section of the config (I didn't know `x=original_dict.get(...); x+=n` would modify `original_dict`!!?!)
