### ISSUE TITLE
vcm.weighted_average removes units

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#1846]
see title.

**Comment by oliverwm1** [comment]
That seems like a useful convenience to me. Other vcm functions already do this, e.g. `vcm.zonal_average_approximate`.

**Comment by mcgibbon** [comment]
This will give incorrect metadata when using weighted average to do e.g. mass weighting. Is that OK? My understanding was that mass weighting is our main use case for weighted averages.

**Comment by mcgibbon** [comment]
I've added a [draft PR for this](https://github.com/ai2cm/fv3net/pull/1855), but it doesn't need to get merged.

**Comment by nbren12** [comment]
Huh? I think this should alway preserve the units of the first argument.
vcm.weighted_average(f, w).units ==  f.units. This function basically
implements this: sum(f*w)/sum(w) so the units of the weights cancel.

**Comment by mcgibbon** [comment]
Ah right, I had this confused with `weighted_sum`. PR is ready for review, then.
