### ISSUE TITLE
make enter_emulation broken

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#1867]
Previously `make enter_emulation` dropped the user in an environment where `external/emulation` could be tested. It no longer works since `projects/microphysics/docker-compose.yml` is gone.

cc @mcgibbon

**Comment by mcgibbon** [comment]
I should have deleted the make target in the last PR, I can update it to use `make enter_prognostic_run` as done in #1868 or delete it if you'd prefer one entrypoint.

All features that were in `enter_emulation` but not in `enter_prognostic_run` were ported over, as far as I could tell. Is there something else missing from `make enter_prognostic_run`? In deciding how to resolve [this issue](https://github.com/ai2cm/fv3net/issues/1821), we concluded it was OK to delete `make enter_emulation` and instead use `make enter_prognostic_run` for the same purpose ([posted in PR](https://github.com/ai2cm/fv3net/pull/1837), discussed in standup and at [team meeting](https://docs.google.com/document/d/11MnJCWqAvVDKbXOeAmxpHcX_pfIgmGCxWh86iTXNYKs/edit#heading=h.yxv6bjqtbvnq)).

FWIW, after I `make enter_prognostic_run`, `cd /fv3net/external/emulation && pytest tests` passes.
