### ISSUE TITLE
Random failures of prognostic run report test

### ISSUE THREAD

**Issue by mcgibbon** [ai2cm/fv3net#1885]
The test_prognostic_run_report test is often [randomly failing on CI](https://app.circleci.com/pipelines/github/ai2cm/fv3net/12157/workflows/88eccee3-8ca8-4980-9016-1a10c3fd099b/jobs/109193) (about 10-30% of the time), possibly due to running out of memory.

This might be solvable by decreasing the size of the test dataset, though it depends on what is actually causing the random failure.

**Comment by oliverwm1** [comment]
Do you know how much memory the CI workers have? Agreed that's probably the issue. This test has also gotten pretty slow—I can work on slimming it down.

**Comment by mcgibbon** [comment]
It looks like they have access to 4GB, based on the [resource usage report](https://app.circleci.com/pipelines/github/ai2cm/fv3net/12157/workflows/88eccee3-8ca8-4980-9016-1a10c3fd099b/jobs/109193/resources). Usage increases sharply towards the end before it crashes.
