### ISSUE TITLE
emulation regression test failing

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#2060]
@spencerkclark found that the fv3net tests don't pass with master of fv3gfs-fortran. In this PR #2047.

# Context

This is the failing test: https://app.circleci.com/pipelines/github/ai2cm/fv3net/13296/workflows/51e0ccfc-8015-44dc-8c8d-5b7ff1982d2f/jobs/122021

After ungarbling the output, the traceback is 
```
Loaded variable metadata from: /fv3net/external/emulation/microphysics_parameter_metadata.yaml
Initialized zarr monitor at: /tmp/tmpfk3n60rq/rundir/state_output.zarr
From cffi callback <function call_function at 0x7f4fe8ee5a60>:
Traceback (most recent call last):
  File "<init code for 'my_plugin'>", line 95, in call_function
  File "/fv3net/external/emulation/emulation/_emulate/microphysics.py", line 94, in microphysics
    predictions = self.model(inputs)
  File "/fv3net/external/emulation/emulation/models.py", line 56, in combined
    x_transformed.update(model(x_transformed))
  File "/fv3net/external/emulation/emulation/models.py", line 43, in __call__
    model_outputs = self.model.predict(inputs, batch_size=self._batch_size)
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/data_adapter.py", line 1653, in _check_data_cardinality
    raise ValueError(msg)
ValueError: Data cardinality is ambiguous:
  x sizes: 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 1, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24
Make sure all arrays contain the same number of samples.
STOP -1
```

@spencerkclark also said this:
> After some debugging I tracked it down to [this PR](https://github.com/ai2cm/fv3gfs-fortran/pull/321) in the fortran model, which is not yet in our existing prognostic run image, but was inadvertently introduced by the fact that I bumped the fortran version.

# Discussion

https://github.com/ai2cm/fv3gfs-fortran/pull/321 added a couple of new outputs in the state dictionary...the rank (a length 1 floating point array) and an area-dependent relative humidity threshold rhc (a 2D variable). rhc is probably not a problem since 
there are other 2D variables like latitude and longitude being passed. My guess is that this is an issue when tensorflow tries batching the effectively scalar rank variable. A simple fix would be to filter out (or broadcast) such scalar values before passing them to `model.predict`.

**Comment by spencerkclark** [comment]
Addressed by @nbren12 in #2062.
