### ISSUE TITLE
Prognostic run configuration hard codes cloud-based 79-level `fv_core.res.nc` asset

### ISSUE THREAD

**Issue by spencerkclark** [ai2cm/fv3net#2197]
By way of [`fv3kube.c48_initial_conditions_overlay`](https://github.com/ai2cm/fv3net/blob/766778a1534d864e542a73c74575fb749abeb933/workflows/prognostic_c48_run/runtime/segmented_run/prepare_config.py#L88-L91), the prognostic run currently hard codes the vertical coordinate file asset to: https://github.com/ai2cm/fv3net/blob/766778a1534d864e542a73c74575fb749abeb933/external/fv3kube/fv3kube/config.py#L22-L26

This presents two possible issues (issue two being the primary current motivation for making this post):
1. If we choose to restart from files with a different number of vertical levels, this hard code will prevent it.
2. Even when restarting from files with 79 vertical levels, this file asset is hard coded to be cloud-based, which is not convenient when running on HPC.  

These can be worked around by patching the config file produced by the `prepare-config` tool with the appropriate path, but this is not a very clean solution.  Would we be open to adding another optional configuration attribute to the [`InitialCondition` dataclass](https://github.com/ai2cm/fv3net/blob/766778a1534d864e542a73c74575fb749abeb933/workflows/prognostic_c48_run/runtime/segmented_run/prepare_config.py#L69-L91) that allowed the user to specify the path to this file?

cc: @mrudko

**Comment by mrudko** [comment]
Hi Spencer,

Thanks for sending me this email. I have been working on submitting ML  training and ML corrected run. I was looking at InitialCondition dataclass before you send me the email. I am right now learning through online tutorial (Real Python website) about dataclasses. Please give me time untill tomorrow and/or the day after tomorrow before I can report to you about the results.

Mike


________________________________
From: Spencer Clark ***@***.***>
Sent: Monday, March 27, 2023 12:02 PM
To: ai2cm/fv3net ***@***.***>
Cc: Mykhailo Rudko ***@***.***>; Mention ***@***.***>
Subject: [ai2cm/fv3net] Prognostic run configuration hard codes cloud-based 79-level `fv_core.res.nc` asset (Issue #2197)


By way of fv3kube.c48_initial_conditions_overlay<https://github.com/ai2cm/fv3net/blob/766778a1534d864e542a73c74575fb749abeb933/workflows/prognostic_c48_run/runtime/segmented_run/prepare_config.py#L88-L91>, the prognostic run currently hard codes the vertical coordinate file asset to: https://github.com/ai2cm/fv3net/blob/766778a1534d864e542a73c74575fb749abeb933/external/fv3kube/fv3kube/config.py#L22-L26

This presents two possible issues (issue two being the primary current motivation for making this post):

  1.  If we choose to restart from files with a different number of vertical levels, this hard-code will prevent it.
  2.  When restarting from files with 79 vertical levels, this file asset is hard coded to be cloud-based, which is not convenient when running on HPC.

These can be worked around by patching the config file produced by the prepare-config tool with the appropriate path, but this is not a very clean solution. Would we be open to adding another optional configuration attribute to the InitialCondition dataclass<https://github.com/ai2cm/fv3net/blob/766778a1534d864e542a73c74575fb749abeb933/workflows/prognostic_c48_run/runtime/segmented_run/prepare_config.py#L69-L91> that allowed the user to specify the path to this file?

cc: @mrudko<https://github.com/mrudko>

**Comment by spencerkclark** [comment]
No worries, @mrudko!  I mostly just wanted to post this here to document the issue and discuss a possible solution before we work on addressing it.  I tagged you so that you would be kept in loop and could engage in the discussion.  I’d be happy to talk more about dataclasses offline.

**Comment by spencerkclark** [comment]
@oliverwm1 FYI this is really the only cloud-file-related issue that came up in doing simulations on HPC.  @mrudko has implemented the solution I suggested.  He is just now working on adding some tests.  

Feel free to weigh in if you have you thoughts, though this approach felt pretty simple and natural, so I didn't necessarily want to bother you right away.

**Comment by oliverwm1** [comment]
Thanks Spencer, your approach of adding an attribute to the `InitialCondition` class sounds good to me.
