### ISSUE TITLE
running fine-resolution simulaiton on Stellar cluster

### ISSUE THREAD

**Issue by mrudko** [ai2cm/fv3net#2202]
Fine-resolution simulation is a major step in Machine Learning(ML) workflow. Trying to perfrom this simulation in a segmented mode (2 consequtive segments in time) on Stellar cluster I have encountered with the error of not being able to find the path to the RESTARTs files. The error message reads

 `raise ConfigError(f"{location_name} location {location} does not exist")
fv3config._exceptions.ConfigError: initial_conditions location [file://](file://scratch/gpfs/mr7417/workflow_segmented/c48_run_2seg/artifacts/20160805.000000/RESTART)[scratch](file://scratch/gpfs/mr7417/workflow_segmented/c48_run_2seg/artifacts/20160805.000000/RESTART)[/gpfs/mr7417/workflow_segmented/c48_run_2seg/artifacts/20160805.000000/RESTART](file://scratch/gpfs/mr7417/workflow_segmented/c48_run_2seg/artifacts/20160805.000000/RESTART) does not exist`

The error originates in the _datastore.py script, which can be found at ../conda/envs/fv3net/lib/python3.8/site-packages/fv3config upon installing conda environment.

`def get_initial_conditions_directory(config):
    """Return the string path of the initial conditions directory
    specified by a config dictionary.
    """
    if "initial_conditions" not in config:
        raise ConfigError("config dictionary must have an 'initial_conditions' key")
    ensure_exists(config["initial_conditions"], "initial_conditions")
    return config["initial_conditions"]

def ensure_exists(location: str, location_name: str):
    if not filesystem.get_fs(location).exists(location):
        raise ConfigError(f"{location_name} location {location} does not exist")`

The possible workaround to this problem suggested by @spencerkclark is replacing  `protocol + "://" + path.lstrip("/")` by the conditional statement in the https://github.com/ai2cm/fv3net/blob/1d0967c5c7f7c347b25ecf7a2ce9ebd363e848ea/external/vcm/vcm/cloud/fsspec.py#L27-L48

e.g.
`if protocol == "file":
     return protocol + "://" + path
  else:
     return protocol + "://" + path.lstrip("/")

This worked well for me and the offline report has been produced. However, this also suggests that there is a bug in the code and more elaborate solution is required.

**Comment by spencerkclark** [comment]
@mrudko thanks for posting these issues to get the conversation started.  For this particular one, the email that you sent me was a much better description of this issue, which relates to the segmented run and not the offline report (the offline report does not interact with restart files).  After getting some sleep (!), please update the description accordingly.

For others I came up with a minimal example that can be reproduced in our prognostic run docker image.  It's probably simplest to create a shell script with the following content in `fv3net/workflows/prognostic_c48_run`, called, say, `example.sh`:

```bash
#!/bin/bash
EXAMPLE_CONFIG=example-config.yaml
COMPILED_CONFIG=compiled-config.yaml
PROGNOSTIC_RUN_ROOT=/example-segmented-run
cat <<EOF > $EXAMPLE_CONFIG
base_version: v0.7
initial_conditions:
  base_url: gs://vcm-ml-experiments/2020-06-02-fine-res/coarsen_restarts
  timestep: "20160805.000000"
namelist:
  coupler_nml:
    days: 0
    hours: 1
    minutes: 0
    seconds: 0
EOF
prepare-config $EXAMPLE_CONFIG > $COMPILED_CONFIG
runfv3 create $PROGNOSTIC_RUN_ROOT $COMPILED_CONFIG
for i in {1..2}
do
    runfv3 append $PROGNOSTIC_RUN_ROOT
done
```

and then enter the docker image and run the script:

```
$ make enter_prognostic_run
$ bash example.sh
```

The example config will be compiled via `prepare-config`, the run will be created, one segment will run, and then the second segment will fail with the following error:

```
2023-04-12 13:00:31.597791: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/esmf/lib:/fv3net/external/fv3gfs-fortran/FMS/libFMS/.libs/:/usr/local/lib
2023-04-12 13:00:31.597843: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Iteration run=/example-segmented-run working_directory=/tmp/tmphg39zh1d
{"step_metadata": {"job_type": "prognostic_run", "url": "/example-segmented-run", "commit": "3b1ff5c9378f6a70c8b760e4f02df373d32de780", "dependencies": null, "args": null, "env_vars": null}}
Continuing from segment file://example-segmented-run/artifacts/20160805.000000
Traceback (most recent call last):
  File "/usr/local/bin/runfv3", line 11, in <module>
    load_entry_point('prognostic-run', 'console_scripts', 'runfv3')()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/fv3net/workflows/prognostic_c48_run/runtime/segmented_run/cli.py", line 57, in append
    sys.exit(api.append(url))
  File "/fv3net/workflows/prognostic_c48_run/runtime/segmented_run/append.py", line 66, in append_segment_to_run_url
    exit_code = run_segment(config, rundir)
  File "/fv3net/workflows/prognostic_c48_run/runtime/segmented_run/run.py", line 27, in run_segment
    fv3config.write_run_directory(config, rundir)
  File "/usr/local/lib/python3.8/dist-packages/fv3config/config/rundir.py", line 22, in write_run_directory
    write_assets_to_directory(config, target_directory)
  File "/usr/local/lib/python3.8/dist-packages/fv3config/_asset_list.py", line 257, in write_assets_to_directory
    asset_list = config_to_asset_list(config)
  File "/usr/local/lib/python3.8/dist-packages/fv3config/_asset_list.py", line 285, in config_to_asset_list
    asset_list += get_initial_conditions_asset_list(config)
  File "/usr/local/lib/python3.8/dist-packages/fv3config/_asset_list.py", line 64, in get_initial_conditions_asset_list
    source_directory = get_initial_conditions_directory(config)
  File "/usr/local/lib/python3.8/dist-packages/fv3config/_datastore.py", line 82, in get_initial_conditions_directory
    ensure_exists(config["initial_conditions"], "initial_conditions")
  File "/usr/local/lib/python3.8/dist-packages/fv3config/_datastore.py", line 88, in ensure_exists
    raise ConfigError(f"{location_name} location {location} does not exist")
fv3config._exceptions.ConfigError: initial_conditions location file://example-segmented-run/artifacts/20160805.000000/RESTART does not exist
```

This has to do with the fact that there needs to be three slashes after `file:` for `fsspec` to recognize the local absolute path:

```
>>> import fv3config
>>> fs = fv3config.filesystem.get_fs("file://example-segmented-run/artifacts/20160805.000000/RESTART")
>>> fs.exists("file://example-segmented-run/artifacts/20160805.000000/RESTART")
False
>>> fs.exists("file:///example-segmented-run/artifacts/20160805.000000/RESTART")
True
```

and the issue is that `vcm.to_url` (called [here](https://github.com/ai2cm/fv3net/blob/3b1ff5c9378f6a70c8b760e4f02df373d32de780/workflows/prognostic_c48_run/runtime/segmented_run/append.py#L29)) removes the leading `"/"` from the input path.

I'm guessing the `lstrip` logic was included to address some issue previously, but I feel like there should be a cleaner way to handle this from an `fsspec` perspective.
