### ISSUE TITLE
`fv3fit_torch` image build fails on trying to install `dgl-cu113`

### ISSUE THREAD

**Issue by spencerkclark** [ai2cm/fv3net#2210]
The `fv3fit_torch` image build is currently failing in CI (e.g. [here](https://app.circleci.com/pipelines/github/ai2cm/fv3net/14348/workflows/1294fcf3-5372-49dc-ba12-93c82ad94c3e/jobs/135099)).  It seems to have occurred in both https://github.com/ai2cm/fv3net/pull/2208 and https://github.com/ai2cm/fv3net/pull/2209, so it may not be a transient issue.  The error has to do with installing a package:

```
#18 [14/14] RUN pip3 install dgl-cu113 dglgo -f https://data.dgl.ai/wheels/repo.html
#18 sha256:e6625a465442fa9ddc44ede99f8e292d1c06e3f08c86e4bf94fb78e728ecdb5c
#18 1.225 Looking in links: https://data.dgl.ai/wheels/repo.html
#18 1.379 ERROR: Could not find a version that satisfies the requirement dgl-cu113 (from versions: none)
#18 1.380 ERROR: No matching distribution found for dgl-cu113
#18 ERROR: executor failed running [/bin/sh -c pip3 install dgl-cu113 dglgo -f https://data.dgl.ai/wheels/repo.html]: exit code: 1
```

cc: @mcgibbon

**Comment by elynnwu** [comment]
Yes, I saw this yesterday, and it went away after a while on its own.

**Comment by spencerkclark** [comment]
Oh good -- thanks @elynnwu -- hopefully nothing to worry about then.

**Comment by spencerkclark** [comment]
Looks like this was fixed upstream https://github.com/dmlc/dgl/issues/5625; our images appear to be building smoothly now too.
