### ISSUE TITLE
Constraints from GitHub break dataflow image build

### ISSUE THREAD

**Issue by spencerkclark** [ai2cm/fv3net#2304]
Since #2267 was merged, [which added a package installed from GitHub to our `constraints.txt` file](https://github.com/ai2cm/fv3net/blob/4cff176a50b3e24b75cb6b5ad5ad85fa47a3f8c7/constraints.txt#L291), the dataflow image build (e.g. [here](https://app.circleci.com/pipelines/github/ai2cm/fv3net/14905/workflows/0bfae3ee-b26d-496f-bd56-c6d9643d38a2/jobs/141963)) has been broken, producing an error when `pip` installing packages:
```
#9 0.743 DEPRECATION: Constraints are only allowed to take the form of a package name and a version specifier. Other forms were originally permitted as an accident of the implementation, but were undocumented. The new implementation of the resolver no longer supports these forms. A possible replacement is replacing the constraint with a requirement. You can find discussion regarding this at https://github.com/pypa/pip/issues/8210.
#9 0.743 ERROR: Unnamed requirements are not allowed as constraints
#9 0.878 WARNING: You are using pip version 21.2.4; however, version 23.2.1 is available.
```
The environment in the build has a different version of `pip` (`21.2.4`) than what we pin in [our `environment.yml` file](https://github.com/ai2cm/fv3net/blob/master/environment.yml) (`20.2.4`).  I encountered a similar issue in the `lint` build, which runs on every commit in each PR, and fixed it by pinning the version `pip` installed in that environment to `20.2.4`.  

In general though, it might be nice to have a solution that worked for newer versions of `pip`.  I think it is orthogonal to this issue, but [the initial issue](https://github.com/ai2cm/fv3net/blob/4cff176a50b3e24b75cb6b5ad5ad85fa47a3f8c7/environment.yml#L18) that prompted pinning `pip` to this version may have been addressed in `pip-tools` (https://github.com/jazzband/pip-tools/issues/1300).

**Comment by brianhenn** [comment]
Agree it would be great to get away from pinning `pip`; it might resolve other issues, e.g., #2266.
