### ISSUE TITLE
Mappm segmentation faults

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#333]
`mappm` has been crashing with segmentation faults on some synthetic data tests as part of #313.

I can work on a MCVE, but I suspect it occurs if delp is negative.

**Comment by mcgibbon** [comment]
Might be fairly easy to fix by wrapping mappm with a check for negative delp and/or nans.

**Comment by mcgibbon** [comment]
I was not able to reproduce this with nans, negative pressures, nor non-monotonic pressures. Any ideas?

**Comment by mcgibbon** [comment]
Started working on this and adding tests in [this PR](https://github.com/ai2cm/fv3net/pull/1854).

**Comment by mcgibbon** [comment]
Closed as not reproducible.
