### ISSUE TITLE
coverage statistics are hard to view

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#461]
It would be nice to add some code coverage tools to this repo, so we can measure the impact a PR has on the coverage, and highlight areas of concern.

**Comment by nbren12** [comment]
this is done but but we don't show coverage information very clearly in PRs...so still worth addressing IMO.

**Comment by mcgibbon** [comment]
What is the fix here?

Currently coverage can be viewed on e.g. [this PR](https://github.com/ai2cm/fv3net/pull/1847#partial-pull-merging) by clicking into the [test_unit results](https://app.circleci.com/pipelines/github/ai2cm/fv3net/11998/workflows/da860894-498c-46fc-9e44-26c154ff0eda/jobs/107403), navigating to the [artifacts tab](https://app.circleci.com/pipelines/github/ai2cm/fv3net/11998/workflows/da860894-498c-46fc-9e44-26c154ff0eda/jobs/107403/artifacts), and scrolling all the way down the list to click on the [index.html](https://output.circle-artifacts.com/output/job/265d5fcc-ce3b-47bf-a99e-09cc53f70c13/artifacts/0/tmp/coverage/htmlcov-test_unit/index.html) from where we can navigate to all files. This is the [suggested way to do it in CircleCI](https://circleci.com/docs/2.0/code-coverage/).

Some things I might be able to do:
- Add a step to the end of the job that echos the HTML link to the coverage report, assuming I can derive it from CircleCI job variables
- separate the coverage report storage into its own job, so it shows up as "Coverage Report" in the list of executed tests on Github
- present to the team how to view the coverage report

**Comment by nbren12** [comment]
Anything to make it visible on the PR page with ideally 0 clicks. It would be awesome if some automation could make a comment/status update with the top level stats (maybe this could be handy: https://cli.github.com/manual/gh_pr_comment).

**Comment by mcgibbon** [comment]
Posting a message every commit could be a lot, but I may be able to restrict it to only post a message when the tests pass which could be more reasonable.

What is the intended use? Is the coverage itself important or the change in coverage?

**Comment by nbren12** [comment]
Both seem important, but moreso the change from a review perspecive. I think it would help us delete defunct or redundant tests or see how much untested new code is being added.
