### ISSUE TITLE
Sign and magntitude errors in rotate_winds_to_lat_lon_coords

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#603]
The meridional winds computed by `vcm.cubedsphere.transform_cubesphere_coords.rotate_winds_to_lat_lon_coords` have a sign error and potentially some problems with their magnitude. See [this analysis](https://github.com/VulcanClimateModeling/explore/blob/671b93f175e4ae1022c559445617c2b50a122d5b/noahb/2020-08-27-wind-emulation/README.md#L36-L36) for more details.

Do we have time to fix these now? If not then maybe we should delete them so they don't confuse future users. Unfortunately, there were no obvious problems with the code. 

FWIW, it would probably be easier to implement these kinds of numerical grid calculations in numpy to avoid fighting against xarray's dimension names and coordinate handling.

cc @AnnaKwa

**Comment by oliverwm1** [comment]
This function no longer exists in VCM. We use the `rotate_xy_winds` function which takes a rotation matrix as an input.
