### ISSUE TITLE
Clarify expected variable names in the FineResolutionResidualCloudsOff mapper

### ISSUE THREAD

**Issue by spencerkclark** [ai2cm/fv3net#670]
It is confusing that if the hybrid nudging mapper is set to add the nudging tendencies from the nudge-to-fine training simulation to the dQ targets, that it expects those tendencies to be named `dQ1` and `dQ2` in the nudging mapper.  

https://github.com/VulcanClimateModeling/fv3net/blob/1e3cee17edd7c913bba5c6e636f01af29da89c6b/external/loaders/loaders/mappers/_hybrid.py#L39-L63

I think it would be clearer to leave those as their standard names from the wrapper, i.e. `air_temperature_tendency_due_to_nudging` and `specific_humidity_tendency_due_to_nudging`, and not requiring renaming them through the opening function.

xref: https://github.com/VulcanClimateModeling/vcm-workflow-control/pull/48#discussion_r493729738

**Comment by nbren12** [comment]
Is this still a valid issue? Maybe we can delete the mapper in question?

**Comment by spencerkclark** [comment]
Yeah I have no problem with deleting the `FineResolutionCloudsOffMapper`.

**Comment by spencerkclark** [comment]
It was already deleted here: https://github.com/ai2cm/fv3net/commit/df0e6673439e2761f88ae90e059b2fd1eeb83679.  Closing this issue.
